# Generated by Django 5.2.6 on 2025-09-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('fab_icon', models.CharField(max_length=64)),
                ('link', models.TextField()),
            ],
        ),
    ]
