# Generated by Django 5.2.6 on 2025-09-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('fab_icon', models.CharField(max_length=64)),
                ('url', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
