# Generated by Django 5.2.6 on 2025-09-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=96)),
                ('tags', models.JSONField()),
                ('links', models.JSONField()),
                ('description', models.TextField(max_length=512)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
